[package]
name = "agama-lib"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agama-settings = { path="../agama-settings" }
anyhow = "1.0"
async-std = "1.12.0"
curl = { version = "0.4.44", features = ["protocol-ftp"] }
futures = "0.3.27"
futures-util = "0.3.27"
jsonschema = { version = "0.16.1", default-features = false }
log = "0.4"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.94"
tempfile = "3.4.0"
thiserror = "1.0.39"
zbus = "3.7.0"
